### ISSUE TITLE
Specify dependencies as toml array

### ISSUE THREAD

**Issue by alexmaco** [hlmtre/homemaker#13]
Toml has builtin support for arrays.
Instead of assigning custom semantics to a string, such as the comma (and maybe space) separation in `dependencies`, the list of dependents could be more idiomatically specified as an array.

The example in the README would then look like:
```toml
[[obj]]
task = 'zt'
solution = 'cd ~/dotfiles/zt && git pull'
dependencies = ['maim', 'slop']
```

If you would be willing to merge this change I can implement it.
